### PR TITLE
Add Selenium tests (WIP)

### PR DESCRIPTION
**Pull request by cdubz**
Working towards #56. Don't merge this yet, please!

:space_invader::space_invader: :space_invader::space_invader::space_invader::space_invader::space_invader::space_invader:
:space_invader::space_invader: :space_invader::space_invader::space_invader::space_invader::space_invader::space_invader:
:space_invader::space_invader:  :space_invader::space_invader::space_invader: :space_invader:
   •

     •

    :small_red_triangle:

### CODE REVIEW

**Comment by cdubz** [comment]
Hmmmm interesting failures in CI - nothing like that locally. Will investigate later.

**Comment by cdubz** [comment]
I looked at this a little bit more this morning and I *can* actually reproduce the inconsistent results with enough tests. Most failures are occurring after `click` and `submit` actions when the test is evaluating existing elements that should have changed. So I think the testing just needs to take advantage of [explicit waits](http://selenium-python.readthedocs.io/waits.html#explicit-waits) on those actions to account for potential slow responses.

**Comment by cdubz** [comment]
Woo no CI errors for once! 🎆

**Comment by overshard** [comment]
Does that mean I should merge it?

**Comment by cdubz** [comment]
Yeah you probably should. I won't be available as much for the rest of this week ): #56 has other needed tests in the check list.

**Pull request merged**
